sudo: false
language: python
python:
  - "2.7"

env:
  - PEBBLE_SDK_VERSION=4.1

before_install:
  - wget https://s3.amazonaws.com/assets.getpebble.com/pebble-tool/pebble-sdk-${PEBBLE_SDK_VERSION}-linux64.tar.bz2
  - mkdir -p ~/.pebble-sdk
  - tar -jxf pebble-sdk-* -C ~/.pebble-sdk
  - touch ~/.pebble-sdk/ENABLE_ANALYTICS
  - export PEBBLE_SDK=~/.pebble-sdk/pebble-sdk-*
  - export PEBBLE=$PEBBLE_SDK/bin/pebble

install:
  - pushd $PEBBLE_SDK
  - virtualenv --no-site-packages .env
  - source .env/bin/activate
  - pip install -r requirements.txt
  - deactivate
  - popd

script:
  - yes | $PEBBLE build
